package com.springboot.meongnyang_Jiphapso.service;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.springboot.meongnyang_Jiphapso.dao.ICartDAO;
import com.springboot.meongnyang_Jiphapso.dao.IOrderDAO;
import com.springboot.meongnyang_Jiphapso.dao.IOrderDetailDAO;
import com.springboot.meongnyang_Jiphapso.dto.CartDTO;
import com.springboot.meongnyang_Jiphapso.dto.OrderDTO;
import com.springboot.meongnyang_Jiphapso.dto.OrderDetailDTO;

@Service
public class OrderService {

	private final IOrderDAO orderDAO;
    private final IOrderDetailDAO orderDetailDAO;
    private final ICartDAO cartDAO;

	@Autowired
	public OrderService (IOrderDAO orderDAO, IOrderDetailDAO orderDetailDAO, ICartDAO cartDAO) {
        this.orderDAO = orderDAO;
        this.orderDetailDAO = orderDetailDAO;
        this.cartDAO = cartDAO;
    }

	@Transactional
	public Long createOrder(Long mNo, List<Long> caNoList, OrderDTO orderInfo) {
        if (caNoList == null || caNoList.isEmpty()) {
            throw new IllegalArgumentException("주문할 상품을 선택해주세요.");
        }

        orderInfo.setMNo(mNo);
        orderDAO.insertOrder(orderInfo);
        Long orNo = orderInfo.getOrNo();

        List<OrderDetailDTO> detailList = new ArrayList<>();
        List<CartDTO> cartItems = new ArrayList<>();
        for (Long caNo : caNoList) {
            CartDTO cart = cartDAO.selectCartOne(caNo);
            if (cart == null) continue;
            cartItems.add(cart);

            OrderDetailDTO detail = new OrderDetailDTO();
            detail.setOrNo(orNo);
            detail.setPNo(cart.getPNo());
            detail.setONo(cart.getONo());
            detail.setOdOptionName(cart.getOName());
            detail.setOdProductName(cart.getPName());
            detail.setOdPrice(cart.getOPrice());
            detail.setOdQuantity(cart.getCaQuantity());
            long amount = (cart.getOPrice() == null ? 0L : cart.getOPrice()) * cart.getCaQuantity();
            detail.setOdAmount(amount);
            detailList.add(detail);
        }
        if (detailList.isEmpty()) {
            throw new IllegalStateException("유효한 장바구니 항목이 없습니다.");
        }

        // dc_order_detail.od_detail_no 가 GENERATED BY DEFAULT AS IDENTITY 인데,
        // INSERT ALL(멀티테이블 insert)로 한번에 넣으면 이 IDENTITY 값이 INTO 절마다가 아니라
        // 소스 행(SELECT 1 FROM DUAL의 1행) 하나당 한 번만 채번돼서, 상품이 2개 이상이면
        // 여러 줄이 같은 od_detail_no를 받으려다 ORA-00001(PK 중복)로 터짐.
        // -> insertOrderDetailList(벌크) 대신 insertOrderDetail(단건)을 하나씩 호출해서
        //    매 INSERT마다 새 IDENTITY 값이 채번되게 함
        for (OrderDetailDTO detail : detailList) {
            orderDetailDAO.insertOrderDetail(detail);
        }

        // 3) 주문 전환된 장바구니 항목 삭제
        cartDAO.deleteCartList(caNoList);

        return orNo;
    }

    /** 주문 상세 조회 (주문상세 목록 포함) */
    public OrderDTO getOrderOne(Long orNo) {
        OrderDTO order = orderDAO.selectOrderOne(orNo);
        if (order != null) {
            order.setOrderDetailList(orderDetailDAO.selectOrderDetailListByOrder(orNo));
        }
        return order;
    }

    public List<OrderDTO> getOrderListByMember(Long mNo) {
        return orderDAO.selectOrderListByMember(mNo);
    }

    public List<OrderDTO> getOrderListByMemberAndStatus(Long mNo, String orStatus) {
        return orderDAO.selectOrderListByMemberAndStatus(mNo, orStatus);
    }

    /** 배송지/메모 등 주문정보 수정 (결제 전에만 허용) */
    @Transactional
    public void updateOrderInfo(OrderDTO orderInfo) {
        orderDAO.updateOrder(orderInfo);
    }

    @Transactional
    public void updateOrderStatus(Long orNo, String orStatus) {
        orderDAO.updateOrderStatus(orNo, orStatus);
    }

    /** 관리자 - 주문 삭제 */
    @Transactional
    public void deleteOrder(Long orNo) {
        orderDAO.deleteOrder(orNo);
    }

    /** 관리자 - 전체 주문 목록 */
    public List<OrderDTO> getAllForAdmin() {
        return orderDAO.selectOrderListAll();
    }

}