spring.application.name=meongnyang_Jiphapso
# JSP ì¤ì Â
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Oracle ì¤ì Â
spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.url=jdbc:log4jdbc:oracle:thin:@192.168.10.107:1521/xe
spring.datasource.username=scott
spring.datasource.password=tiger

# MyBatis ì¤ì Â Â
#mybatis.config-location=classpath:mybatis-config.xml
mybatis.mapper-locations=classpath:mybatis/mapper/**.xml

# spring.servlet.multipart.enabled = true ë¤ì¤íì¼ì¬ë¶ ê¸°ë³¸ê°Â
# ìµë íì¼ í¬ê¸° ì¤ì  (ê¸°ë³¸ê° : 1MB)
spring.servlet.multipart.max-file-size = 30MB
# ìµë ìì²­ í¬ê¸° ì¤ì  (ê¸°ë³¸ê° : 1MB)
spring.servlet.multipart.max-request-size = 300MB

spring.elasticsearch.uris=http://192.168.10.107:9200


# 결제 연동
portone.store-id=store-35335759-6047-4991-9a70-706bda2091f7
portone.api-secret=Psk4qFzbYft1xVvNH1nYIJcODQe72L3TR3wlKwwSAz3BgUO3EjGzmDSdIrSbYeT2d6YYV2c0JUbEbfmi
portone.channel-key.tosspay=channel-key-771f5995-0b68-4980-a34d-eba981c7f934
portone.channel-key.kakaopay=channel-key-d35f3bf5-b961-4412-94d3-b912d5af5abe
portone.channel-key.naverpay=channel-key-601aa754-26e8-47ef-bb40-4e7f15933514
portone.channel-key.payco=
portone.channel-key.smilepay=