# \uC5EC\uAE30\uC5D4 \uC55E\uC73C\uB85C API\uD0A4\uB4E4\uC744 \uB123\uC744\uAC70\uC784(\uADF8\uB0E5 git\uC5D0 \uC62C\uB9AC\uBA74 \uD0A4\uAC00 \uC678\uBD80\uC5D0 \uB178\uCD9C\uB418\uC5B4\uC11C \uC704\uD5D8\uD558\uB2E4 \uCE85\uB2C8\uB2E4)

# \uACB0\uC81C \uC5F0\uB3D9 (PortOne) - \uAC1C\uC778 \uC2A4\uD1A0\uC5B4 \uD0A4\uB85C \uBC1C\uAE09\uBC1B\uC544 \uCC44\uC6CC\uB123\uAE30
portone.store-id=store-35335759-6047-4991-9a70-706bda2091f7
portone.api-secret=Psk4qFzbYft1xVvNH1nYIJcODQe72L3TR3wlKwwSAz3BgUO3EjGzmDSdIrSbYeT2d6YYV2c0JUbEbfmi
portone.channel-key.tosspay=channel-key-771f5995-0b68-4980-a34d-eba981c7f934
portone.channel-key.kakaopay=channel-key-d35f3bf5-b961-4412-94d3-b912d5af5abe
portone.channel-key.naverpay=channel-key-601aa754-26e8-47ef-bb40-4e7f15933514
portone.channel-key.payco=
portone.channel-key.smilepay=

# \uCC57\uBD07 \uC5F0\uB3D9 (Gemini)
spring.ai.google.genai.api-key=AQ.Ab8RN6KY6Kx4Ew9O8jZJHcUJJCFfDMQcPLcuoq9B0c1jxfIxHA
spring.ai.google.genai.chat.options.model=gemini-3.6-flash