# 여기엔 앞으로 API키들을 넣을거임(그냥 git에 올리면 키가 외부에 노출되어서 위험하다 캅니다)

# 결제 연동 (PortOne) - 개인 스토어 키로 발급받아 채워넣기
portone.store-id=store-35335759-6047-4991-9a70-706bda2091f7
portone.api-secret=Psk4qFzbYft1xVvNH1nYIJcODQe72L3TR3wlKwwSAz3BgUO3EjGzmDSdIrSbYeT2d6YYV2c0JUbEbfmi
portone.channel-key.tosspay=channel-key-771f5995-0b68-4980-a34d-eba981c7f934
portone.channel-key.kakaopay=channel-key-d35f3bf5-b961-4412-94d3-b912d5af5abe
portone.channel-key.naverpay=channel-key-601aa754-26e8-47ef-bb40-4e7f15933514
portone.channel-key.payco=
portone.channel-key.smilepay=

# 챗봇 연동 (Gemini)
spring.ai.google.genai.api-key=AQ.Ab8RN6KY6Kx4Ew9O8jZJHcUJJCFfDMQcPLcuoq9B0c1jxfIxHA
spring.ai.google.genai.chat.options.model=gemini-3.6-flash